Repository suryapratapsinghsuryavanshi/solverjs, pull requests merged in 2021-10, with the labels that each got.

#4 Optimized fac & sumOfN functions
  src/math/math.js
Labels: enhancement, hacktoberfest

#5 Fix typing errors.
  README.md
Labels: documentation, hacktoberfest

#6 fix typing error
  README.md
Labels: documentation, hacktoberfest

#9 Add description for methods
  README.md
Labels: documentation, enhancement, hacktoberfest
